language: cpp
addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
        packages:
            - g++-5
            - gcc-5
            - cmake
            - cmake-data
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
matrix:
  exclude:
    - os: osx
      compiler: gcc
script:
  - mkdir build && cd build && cmake .. && make -j2
sudo: required
branches:
  only:
    - master
notifications:
  email: false

